---
- name: '[dependencies] Install parted and dirmngr'
  apt:
    name:
      - parted
      - dirmngr
    update_cache: yes
    state: present
    force: yes
  become: yes
  tags:
    - expandfs
    - expandfs_dependencies

- name: '[dependencies] Add the GPG key of the apt-get repository for raspbian stretch'
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7FA3303E
    state: present
  when: ansible_distribution_release == 'stretch'
  tags:
    - expandfs
    - expandfs_dependencies

- name: '[dependencies] Add apt-get repositories for raspbian stretch to install raspi-config and firmware'
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi firmware
    - deb http://archive.raspberrypi.org/debian/ stretch main ui     # holds raspi-config package
  when: ansible_distribution_release == 'stretch'
  tags:
    - expandfs
    - expandfs_dependencies

- name: '[dependencies] Install raspi-config'
  apt:
    name: raspi-config
    update_cache: yes
    state: present
    force: yes
  become: yes
  tags:
    - expandfs
    - expandfs_dependencies
...
